### ISSUE TITLE
Update GUI for Docker use

### ISSUE THREAD

**Issue by mwakok** [SATAY-LL/Transposonmapper#3]
- [x]  Be able to use custom adapters file from /data folder inside Docker container
- [x] Add first use instructions (both separate documentation and message in GUI)
- [x] Button for help documentation (-h flag)
- [x] Add trimmomatic argument support

**Comment by leilaicruz** [comment]
I remove the option in the GUI to trim with trimmomatic.

See https://github.com/SATAY-LL/Transposonmapper/pull/44 for the changes made

For the addition of a button directing to the web documentation see this issue: https://github.com/SATAY-LL/Transposonmapper/issues/45
