### ISSUE TITLE
Not accepting relative paths during run on the local docker container

### ISSUE THREAD

**Issue by leilaicruz** [SATAY-LL/Transposonmapper#31]
**Describe the bug**
Not accepting relative paths during run on the local docker container 

![image](https://user-images.githubusercontent.com/11459658/125637643-55f90379-5a3e-4c90-a276-41ebf9deea57.png)

**To Reproduce**
1. Go to the Transposonmapper folder location
2. Build the docker image : `docker build . -t leilaicruz/satay`
3. Go to the data folder to mount in the docker container
4.  `docker run --rm -it --net=host -e DISPLAY=:0 -v $(pwd):/data leilaicruz/satay`
5.  See the error

**Expected behavior**
It is expected to understand the relative paths in the transposonmapper main function 
![image](https://user-images.githubusercontent.com/11459658/125638145-7a7f07d6-53cd-49ae-a0b7-15edc3ebb0c8.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by mwakok** [comment]
I pushed a solution to the `package_in_dockerfile` branch. Please check if this works.

**Comment by mwakok** [comment]
Should be working now. I have a pushed the following changes:
- Create a separate script `satay_transposonmapper.py` to import the transposonmapper module
- Create separate folder with satay scripts
- Update conda environments
- Update Dockerfile

**Comment by leilaicruz** [comment]
Yes I am testing it now, I pull from the `package_in_dockerfile` branch. Once it passed we should merge with develop , since you also had to change the name of the `transposonmapping_satay.py`. So then I can continue working with that structure,

Thanks!

**Comment by leilaicruz** [comment]
It runs! , the only thing to keep in mind is that when defining the new adapter file after  the 1st analysis , we have to define it in reference to the location of the satay.sh file. Usually the container is directly inside the `data/` folder, so:
`adapters=../../data/adapters.fa ` would be the new location assigned to the adapter file in reference to where is satay.sh 

I will make a pull request of this and merge it in develop .
