### ISSUE TITLE
Workshop

### ISSUE THREAD

**Issue by leilaicruz** [SATAY-LL/Transposonmapper#40]

**Comment by leilaicruz** [comment]
List of people: 
- Enzo Kingma (user/developer)
- Floor Dolsma (user)
- Liedewij Laan (user)
- Thomas Wisse (user)
- Els Sweep (observer)

**Comment by mwakok** [comment]
@leilaicruz Proposal invitation:

Dear all,

We would like to invite you to attend a two-part knowledge transfer session to go over the SATAY and transposonmapper data pipelines. Over the past few months we have improved the code base by introducing Docker containers, creating software modules, adding tests, and improving the documentation. 

We would like to schedule two sessions, the first for users (and developers) of SATAY and the second for (potential) developers of the code base. Below, you can find a summary of the content per day.

For possible dates, we are looking at the **22nd, 23rd, 29th, and 30th of September at 09:30-12:00**. Please let us know which sessions you would like to attend and which days would suit you. In case you can't attend, we will also record the sessions and the documentation should provide a good starting point.

**Session 1 - Users**
- Docker
    - Introduction
    - Basic Docker commands
    - Set up SATAY container
    - Run processing pipeline
 - Transposonmapper
     - Installation and usage
     - Features and examples
 - Documentation

**Session 2 - Developers**
-  Collaborative software development
    - Branch management with GitFlow
    - Conda environments
    - Modular code and unit tests
    - Overview Continuous Integration with GitHub Actions
- Docker
    - Dockerfile
    - Creating a Docker image

**Comment by mwakok** [comment]
Dear all,

We are looking forward again to the SATAY Workshop session on Thursday from 09:30-12:00. We will be focusing on topics relevant for developers, touching upon collaborative coding, conda environments, modular code, testing, continuous integration, and Docker. 

**Important** - if you were not able to join the previous session, there are some steps we ask you to take **prior to Thursday’s session** to get your environment set up and join us where we left off. In case you encounter installation issues, feel free to join the session 15 minutes earlier at 09:15. Alternatively, you can post your issues below, so we can document them.

Installation instructions:

1.	Install [Anaconda Navigator](https://carpentries.github.io/workshop-template/#python)
2.	Install [GitBash](https://carpentries.github.io/workshop-template/#shell-windows) (for Windows) or [git](https://carpentries.github.io/workshop-template/#git-macos) (for macOS and Linux) 
3.	Install Docker by following our instructions and troubleshooting guide [here](https://satay-ll.github.io/Transposonmapper/03-docker-doc/01-Docker-Setup.html).
4.	Install [VSCode](https://code.visualstudio.com/)
5.	Check that software installation was successful
a.	Open [Terminal (on Mac)](https://support.apple.com/en-gb/guide/terminal/apd5265185d-f365-44cb-8b09-71a064a42125/mac#:~:text=Open%20Terminal,%2C%20then%20double%2Dclick%20Terminal.) or [GitBash (Windows)](https://www.codecademy.com/articles/command-line-setup)
b.	In your terminal, type: `conda --version` and hit ‘Enter’. You should see an output in the command window with conda followed by the version number. This means Anaconda is installed correctly.
c.	In your terminal, type `python --version` and hit ‘Enter’. You should see an output in the command window with the python version number, probably 3.8.x. 
d.	In your terminal, type: `git version` and hit ‘Enter’. You should again see output that says Git followed by some version number indicating a successful install. 
e.	With docker running, type `docker --version` in your terminal (outputting a version number) and type `docker run hello-world` to see a welcoming message. 
6.	If you haven’t used git before, configure your Git global settings 
a.	In the terminal again, type: `git config --global user.name "Your Name"` and hit ‘Enter’. Of course replace Your Name inside the quotes with your actual name, keeping the quotes. 
b.	In the terminal, type: `git config --global user.email yourname@example.com` and hit ‘Enter’. Replace your real email address here, note that you do not have to use quotes in this command.
c.	In the terminal, type: `git config --list` and hit ‘Enter’. You should see your name and email address in the global settings. 

With this, you should be all set!
