### ISSUE TITLE
Reorganize Juptyerbook content

### ISSUE THREAD

**Issue by mwakok** [SATAY-LL/Transposonmapper#51]
- Intro (purpose of software, audience, what does it solve, summary)
- Getting started (installation, first time use)
- API (calling functions, general features, package modules)
- Scientific background
- Community guidelines
- Tutorials

**Comment by mwakok** [comment]
Jupyter-book offers automatic compiling of all the docstrings into an API reference via `sphinx`: https://jupyterbook.org/advanced/developers.html.

**Comment by leilaicruz** [comment]
that is great , I will try it!

**Comment by leilaicruz** [comment]
I have tried it but  I havent succed... can you look at the file [api.rst](https://github.com/SATAY-LL/Transposonmapper/blob/update_doc/jupyter_book/api.rst) and the [config file](https://github.com/SATAY-LL/Transposonmapper/blob/update_doc/jupyter_book/_config.yml) to see if I made something wrong ? 

Now the jupyter Book is loaded in the same repo in the [gh-pages](https://github.com/SATAY-LL/Transposonmapper/deployments/activity_log?environment=github-pages)

**Comment by mwakok** [comment]
I have pushed a new version and the API refernces are working. I think you made a mistake in the location of the build api html files. I had to delete a `_build` folder and `api.html` that were created outside the jupyter_book folder.

I also took the opportunity to reorganize the toc and some of the Docker pages. I feel we still need quite some more updating to make it easy for users and developers to find what they're looking for.

Also, since the docstrings are now parsed in the [Numpy style](https://numpydoc.readthedocs.io/en/latest/format.html), we need to make sure all docstrings adhere to this style. Not all docstrings are currently rendered properly.

**Comment by leilaicruz** [comment]
I have pull from it and when I do a local build I do not see the api reference :

![image](https://user-images.githubusercontent.com/11459658/131511487-34931cba-e6ef-4851-8a44-729a8ec80777.png)

It is weird, I dont have a folder of  `_build` outside the jupyter_book folder neither an `api.html` file ....
