### ISSUE TITLE
add a github action workflow for the publishing of the jupyter Book

### ISSUE THREAD

**Issue by leilaicruz** [SATAY-LL/Transposonmapper#52]

**Comment by mwakok** [comment]
I have added a workflow called `CI_deploy_book.yml` to the update_doc branch. This is based on the example from [jupyter-book](https://jupyterbook.org/publish/gh-pages.html). The action still needs to be tested though. 

As the action fully builds the jupyter-book, I think it's best to remove the folder `./jupyter_book/_build/` from the repo and add it to the gitignore as it is generated content that's no longer required.

**Comment by mwakok** [comment]
This workflow is active.
